name: Python application

on:
  pull_request:
    branches:
      - '**'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Update CA certificates
      run: |
        sudo apt install ca-certificates
        sudo update-ca-certificates --fresh
        export SSL_CERT_DIR=/etc/ssl/certs

    - name: Run tests
      env:
        DATABASE_URL: "sqlite:///:memory:"
        FLASK_APP: src
        JWT_SECRET_KEY: super_secret_key
      run: |
        pytest